### ISSUE TITLE
Null Reference exception in XfxEntryRendererDroid 

### ISSUE THREAD

**Issue by BryanSan** [XamFormsExtended/Xfx.Controls#22] opened 2017-07-15 14:30 UTC
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 
I received a hockey app crash report like 4 times, just a null reference exception, its happen only in Android.

android.runtime.JavaProxyThrowable: System.NullReferenceException: Object reference not set to an instance of an object

Xfx.Controls.Droid.Renderers XfxEntryRendererDroid get_EditText 1 Xfx.Controls.Droid.Renderers XfxEntryRendererDroid+<>c__DisplayClass12_0 <ControlOnFocusChange>b__0 2 Java.Lang Thread+RunnableImplementor Run 3 Java.Lang IRunnableInvoker n_Run 4 mono.java.lang RunnableImplementor n_run 5 mono.java.lang RunnableImplementor run 6 android.os Handler handleCallback 7 android.os Handler dispatchMessage 8 android.os Looper loop 9 android.app ActivityThread main 10 java.lang.reflect Method invoke 11 com.android.internal.os ZygoteInit$MethodAndArgsCaller run 12 com.android.internal.os ZygoteInit main Ja va.Lang.Thread 

* Version Number of Control:
1.0.4

* Device Tested On:
Huawey P9.

* Simulator Tested On:
x86 API 24

### Expected Behavior
Dont Crash

### Actual Behavior
Crash

### Steps to reproduce the Behavior
I cant reproduce the exception :( I think if you do something while the animation of the edit text is running it crash

## Feature Request:
I think we need a null check in this line in the XfxEntryRendererDroid class
line 36:  private EditText EditText => Control.EditText;

**Comment by ChaseFlorell** [comment] 2017-08-28 00:27
I've added a null check here but I cannot reproduce the issue. I suggest getting a repro and I will fix it.

Closing with 4edf928

**Closed by ChaseFlorell** 2017-08-28 00:27 UTC

**Comment by AEA94** [comment] 2018-11-10 13:57
Unfortunately the problem still remains in Version 1.1.3.
Last part of my Callstack:

System.Diagnostics.Debugger.Mono_UnhandledException(System.NullReferenceException ex) 
object.25( Parameters)
Xfx.Controls.Droid.Renderers.XfxEntryRendererDroid.get_EditText() 

It works on iOS but crashes on Android. Seems to be a missing null check

**Comment by mrbelk** [comment] 2018-12-11 18:20
I've gotten a few MS AppCenter crash reports for this lately, too. Android version 6.0.1

The stack trace is pretty limited, but here it is:

```
XfxEntryRendererDroid.get_EditText ()
XfxEntryRendererDroid+<>c__DisplayClass12_0.<ControlOnFocusChange>b__0 ()
Thread+RunnableImplementor.Run ()
IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this)
(wrapper dynamic-method) System.Object.54(intptr,intptr)
```
